### ISSUE TITLE
rnv new fails

### ISSUE THREAD

**Issue by aamalric** [pavjacko/renative#388]
Hi I'm new to RNV and after installing the rnv package globally, I have an error doing the rnv new like the documentation says

**To Reproduce**
1. Run command 'rnv new'
2. See error:
`┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.28.14                                                      │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv new                                                             │
│        Start Time: 2020-1-15 15:46:18                                        │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

$ rnv new - cli - Starting!
$ rnv new - initializeBuilder:false - Starting!
$ rnv new - checkAndMigrateProject - Starting!
$ rnv new - listAppConfigsFoldersSync:undefined - Starting!
$ rnv new - _migrateProjectSoft - Starting!
$ rnv new - parseRenativeConfigs - Starting!
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:6:3:0
$ rnv new - _getWorkspaceDirPath - Starting!
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:6:3:1
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:6:3:1
$ rnv new - configureRnvGlobal - Starting!
$ rnv new - createNewProject - Starting!
? What's your project Name? (no spaces, folder based on ID will be created in this directory) test
? What's your project Title? Hello Renative
? What's your App ID? com.mycompany.test
? What's your Version? 0.1.0
? What workspace to use? rnv
$ rnv new - parseRenativeConfigs - Starting!
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:7:3:3
$ rnv new - _getWorkspaceDirPath - Starting!
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:7:3:3
$ rnv new - generateBuildConfig - Starting!
$ rnv new - generateBuildConfig:18:7:3:3
? What template to use? renative-template-hello-world
⠏ Executing: npm view renative-template-hello-world versions┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2020-1-15 15:46:27                                            │
│  $ rnv new                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  Env Info: linux | x64 | node v8.17.0 | rnv v0.28.14                         │
│  Executed Time: 0h:0m:8s:562ms                                               │
│                                                                              │
│ 🛑  $ rnv new - ERRROR! _child4$stdout.off is not a function
TypeError: _child4$stdout.off is not a function
    at off (/usr/lib/node_modules/rnv/src/systemTools/exec.js:107:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
⠦   '0.28.17-alpha.1' ]`

**Desktop (please complete the following information):**
 - OS: linux x64 Ubuntu 16.04 LTS
 - Node Version v8.17.0
 - RNV Version v0.28.14

**Additional context**
I didn't customize anything, all configuration files are the default ones.

**Comment by aamalric** [comment]
Seems like I didn't had installed the correct version of node, so using nvm to manage mutliple version of node, I restarted the install with node v10.13.0 but now I have issues launching rnv: 

`
Error: The module '/home/aamalric/.nvm/versions/node/v10.13.0/lib/node_modules/rnv/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

`

**Comment by aamalric** [comment]
Ok nevermind, the default node version wasn't the correct one, missed a configuration step in my nvm setup.
