### ISSUE TITLE
npx rnv clean fails: 'watchman' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by TheDuc** [pavjacko/renative#488]
**Describe the bug**
watchman is not installed globally. When running `npx rnv clean` and answering yes to all, the command eventually fails. Log output:
```
_execute: watchman watch-del-all
× FAILED: watchman watch-del-all
'watchman' is not recognized as an internal or external command,
operable program or batch file.

│ 🛑  $ rnv clean --info - ERRROR! COMMAND:

watchman watch-del-all

FAILED with ERROR:

Error: Command failed with exit code 2 (ENOENT): watchman watch-del-all
spawn watchman ENOENT
    at notFoundError (C:\Users\[username]\AppData\Roaming\npm-cache\_npx\7376\node_modules\rnv\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\[username]\AppData\Roaming\npm-cache\_npx\7376\node_modules\rnv\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\[username]\AppData\Roaming\npm-cache\_npx\7376\node_modules\rnv\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**Additional context**
Maybe this can be solved by adding `npx` before the watchman command at https://github.com/pavjacko/renative/blob/ece6c865e9c91077eb65fc2b127b02a94ac88fce/packages/rnv/src/systemTools/cleaner.js#L117

**Comment by pavjacko** [comment]
@TheDuc  fixed in `0.29.1-alpha.7`
