### ISSUE TITLE
Can't create appConfig file on windows

### ISSUE THREAD

**Issue by JohnLiber** [pavjacko/renative#496]
System:
-   OS: Windows 10
-   Node Version: v12.16.1
-   RNV Version: 0.29

1. Run 'rnv new' and follow setup
2. cd project
3. rnv run android 

Results in the following error code bellow:

`⚠️  $ rnv run android - WARNING: Template file C:\Users\User\Desktop\React Projects\sas\node_modules\renative-template-blank\package.json\renative.template.json does not exist. check your C:\Users\User\Desktop\React Projects\sas\node_modules\renative-template-blank\package.json. skipping
│ ⚠️  $ rnv run android - WARNING: No app configs found for this project
│ ⚠️  $ rnv run android - WARNING: c.paths.appConfig.config at path: C:\Users\User\Desktop\React Projects\sas\appConfigs\helloWorld\renative.json does not exist. ReNative will regenerate renative.local.json
│ 🛑  $ rnv run android - ERRROR! Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\src\templateTools\index.js:322:22)
    at tryCatch (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:97:21)
    at tryCatch (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:45:40)
    at invoke (C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:135:20)
    at C:\Users\User\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:145:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by JohnLiber** [comment]
Anyone know how to fix this?

**Comment by TalhaArshad** [comment]
I am also facing this issue. 
OS: Windows 10
Node v: v12.16.1
RNV v: 0.29

Any suggestions?

**Comment by pavjacko** [comment]
@TalhaArshad @JohnLiber looks like build config has not been generated properly or at all.
I'm back at my Win desktop morning. will investigate

**Comment by pavjacko** [comment]
Issue will be tackled by #509

**Comment by pavjacko** [comment]
Alpha release now available `0.29.1-alpha.12`
