### ISSUE TITLE
0.29.1-alpha.8 detects all platforms as ejected + web run is failing

### ISSUE THREAD

**Issue by CHaNGeTe** [pavjacko/renative#510]
**Describe the bug**
alpha.8 is detecting all platforms as being ejected.
I think it is leading to some issues running web

**To Reproduce**
1. Create a project with rnv alpha.7 and don't eject it.
2. Check `npx rnv@0.29.1-alpha.7` output
3. Check `npx rnv@0.29.1-alpha.8` output 
4. See error, all platforms are ejected.
5. See error (part 2), run `rnv run -p web`, it complains about missing config files (it is indeed looking for them on `platformTemplates` as is the platform was ejected.

**Expected behavior**
Platforms not being detected as ejected + web run working

**Screenshots or copy&paste**
**alpha.7:**
```
$ rnv platform eject - rnvPlatformEject - Starting!
? This will copy platformTemplates folders from ReNative managed directly to your project Select platforms you would like to connect (Press <space> to select, <a> to toggle all, <i> to inv
ert selection)
❯◯ ios - (connected)
 ◯ android - (connected)
 ◯ androidtv - (connected)
 ◯ androidwear - (connected)
 ◯ web - (connected)
 ◯ tizen - (connected)
 ◯ tvos - (connected)
```

**alpha.8:**
```
$ rnv platform eject - rnvPlatformEject - Starting!
? This will copy platformTemplates folders from ReNative managed directly to your project Select platforms you would like to connect (use SPACE key) (Press <space> to select, <a> to toggle
 all, <i> to invert selection)
 - ios - (ejected) (Disabled)
 - android - (ejected) (Disabled)
 - androidtv - (ejected) (Disabled)
 - androidwear - (ejected) (Disabled)
 - web - (ejected) (Disabled)
 - tizen - (ejected) (Disabled)
 - tvos - (ejected) (Disabled)
```

**run web with alpha.8:**
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  :rocket:  SUMMARY | 5/29/2020, 09:55:26                                           │
│  $ rnv run -p web                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.29.1-alpha.8                                            │
│  Project Name: @24i/prd-nxg-sdk-media                                        │
│  Project Version: 0.12.48                                                    │
│  App Config: tmmedia-nextgen-sdk-neutron-testerexample                       │
│  Workspace: nextgen                                                          │
│  Supported Platforms: ios(ejected), android(ejected),                        │
│  androidtv(ejected), androidwear(ejected), web(ejected), tizen(ejected),     │
│  tvos(ejected), webos(ejected), macos(ejected), windows(ejected),            │
│  tizenwatch(ejected), kaios(ejected), firefoxos(ejected), firefoxtv(ejected) │
│  Env Info: darwin | x64 | node v12.16.1                                      │
│  Platform: web                                                               │
│  Executed Time: 0h:0m:1s:334ms                                               │
│                                                                              │
│ :warning:  $ rnv run -p web - WARNING: No Match found in /Users/dmr24i/Desktop/WIP/prd-nxg-sdk-media/node_modules/@react-native-community/blur/ios/BlurView.m for expression: #if defined.__IPHONE_OS_VERSION_MAX_ALLOWED. && __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000.
Consider update or removal of /Users/dmr24i/Desktop/WIP/prd-nxg-sdk-media/appConfigs/base/plugins/@react-native-community/blur/overrides.json
│ :octagonal_sign:  $ rnv run -p web - ERRROR! ENOENT: no such file or directory, open '/Users/dmr24i/Desktop/WIP/prd-nxg-sdk-media/platformTemplates/web/_privateConfig/webpack.config.dev.js'
Error: ENOENT: no such file or directory, open '/Users/dmr24i/Desktop/WIP/prd-nxg-sdk-media/platformTemplates/web/_privateConfig/webpack.config.dev.js'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at readFileSync (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/src/systemTools/fileutils.js:26:24)
    at _generateWebpackConfigs (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/src/platformTools/web/index.js:115:5)
    at _generateWebpackConfigs (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/src/platformTools/web/index.js:198:5)
    at tryCatch (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/Users/dmr24i/.npm/_npx/69860/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:135:20)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Desktop:**

-   OS: osx
-   Node Version v12.16.1
-   RNV Version 0.29.1-alpha.8

**Comment by pavjacko** [comment]
@CHaNGeTe tested with `0.30.0`. should work correctly now
