### ISSUE TITLE
Error: Command failed with exit code 1 (EPERM): ./gradlew assembleDebug -x bundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by Ivanov89** [pavjacko/renative#532]
Аfter hitting `rnv run -p android` it crashed with the following error,after loading the android emulator:

**To Reproduce**
Just run `rnv run -p android` in the terminal

<img width="728" alt="Screenshot 2020-06-25 at 13 12 28" src="https://user-images.githubusercontent.com/4004486/85832066-13018480-b798-11ea-8d9a-af1996a718bc.png">

**Desktop (please complete the following information):**

-   OS:  macOS Catalina 10.15.5
-   Node Version: 0.30.2-alpha.2
-   RNV Version: 0.30.2-alpha.2

Tried to clean the gradle with `./gradlew clean` but it fails again

Thank you

**Comment by pavjacko** [comment]
@Ivanov89 could you upgrade `rnv` to final `0.30.2`. there were some extra fixes added before final release

**Comment by Ivanov89** [comment]
@pavjacko , the error still exists unfortunately:

`│ ⚠️  $ rnv run -p android -r - WARNING: You are running $rnv v0.30.3 against project built with rnv v0.30.2-alpha.2. This might result in unexpected behaviour!
It is recommended that you run your rnv command with npx prefix: $ npx rnv run -p android -r . or manually update your devDependencies.rnv version in your package.json.
│ ✅ Found active emulator! emulator-5554. Will use it
│ 🛑  $ rnv run -p android -r - ERRROR! COMMAND: 

./gradlew assembleDebug -x bundleReleaseJsAndAssets 

FAILED with ERROR: 

Error: Command failed with exit code 1 (EPERM): ./gradlew assembleDebug -x bundleReleaseJsAndAssets
    at makeError (/usr/local/lib/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/rnv/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────⠋ emulator: INFO: QtLogger.cpp:68: Warning: Failed to get QCocoaScreen for NSObject(0x0) ((null):0, (null))%    `

**Comment by pavjacko** [comment]
Hmm then it might be something different.  can you run `rnv run -p android -r -i` and post the error log there should be more detailed gradle error visible

**Comment by Ivanov89** [comment]
So this is the error log after hitting `rnv run -p android -r -i` :

`2020-06-26T14:13:40.791+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
undefined
generateOptions true
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 6/26/2020, 2:13:41 PM                                         │
│  $ rnv run -p android -r -i                                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.30.3                                                    │
│  Project Name ($package.name): CMSCasino                                     │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): android                                                      │
│  Engine ($.platforms.android.engine): engine-rn                              │
│  App Config (-c): cmscasino-stage                                            │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: android(ejected), ios(ejected)                         │
│  Env Info: darwin | x64 | node v12.12.0                                      │
│  Executed Time: 0h:0m:10s:723ms                                              │
│                                                                              │
│ ⚠️  $ rnv run -p android -r -i - WARNING: platformTemplatesDirs should be placed inside "paths" object in your /Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino/renative.json
│ ⚠️  $ rnv run -p android -r -i - WARNING: Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ ⚠️  $ rnv run -p android -r -i - WARNING: Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ 🛑  $ rnv run -p android -r -i - ERRROR! COMMAND: 

./gradlew assembleDebug --debug -x bundleReleaseJsAndAssets 

FAILED with ERROR: 

Error: Command failed with exit code 1 (EPERM): ./gradlew assembleDebug --debug -x bundleReleaseJsAndAssets
    at makeError (/usr/local/lib/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/rnv/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘`

**Comment by pavjacko** [comment]
@Ivanov89 
strange if you getting ONLY `DaemonClientConnection] thread 1: connection stop` and nothing else.

I noticed your platforms (android, ios) are marked as ejected. is that on purpose? if not can you remove `platformTemplatesDirs` from your `renative.json` manually or run `rnv platform connect`
and try `rnv run -p android -r -i` again so your project will use latest native templates


Further down you could navigate to `./platformBuilds/cmscasino-stage_android` and run `./gradlew assembleDebug --debug -x bundleReleaseJsAndAssets` manually if something obvious pops up

**Comment by CiaranPearse** [comment]
I fixed this exact error by removing the dash (-) from my project name everywhere. I had an error further up that said
`AAPT: error: attribute 'android:name' in <activity> tag must be a valid Java class name.`

Looks like you have folders named cms-casino. Try renaming to cmsCasino

**Comment by Ivanov89** [comment]
@pavjacko , 
I need that platforms to be ejected, 
and I still cannot run neither on simulator, neither on device, the following error occurs:

`BUILD FAILED in 791ms
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 7/6/2020, 11:42:11 AM                                         │
│  $ rnv run -p android -d                                                     │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.30.3                                                    │
│  Project Name ($package.name): CMSCasino                                     │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): android                                                      │
│  Engine ($.platforms.android.engine): engine-rn                              │
│  App Config (-c): cmscasino-stage                                            │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: android(ejected), ios(ejected)                         │
│  Env Info: darwin | x64 | node v12.12.0                                      │
│  Executed Time: 0h:0m:6s:981ms                                               │
│                                                                              │
│ ⚠️  $ rnv run -p android -d - WARNING: platformTemplatesDirs should be placed inside "paths" object in your /Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/renative.json
│ ⚠️  $ rnv run -p android -d - WARNING: Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ ⚠️  $ rnv run -p android -d - WARNING: Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ 🛑  $ rnv run -p android -d - ERRROR! COMMAND: 

./gradlew assembleDebug -x bundleReleaseJsAndAssets 

FAILED with ERROR: 

Error: Command failed with exit code 1 (EPERM): ./gradlew assembleDebug -x bundleReleaseJsAndAssets
    at makeError (/usr/local/lib/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/rnv/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
` 
Will be appreciate if that can be fixed, because I am blocked now... 
Thank you !

**Comment by pavjacko** [comment]
@CiaranPearse ok so wrt Activity. 

by default AndroidManifest.xml is generated with 

```
...
<activity
          android:name=".MainActivity"
...
```

that should correspond to EXACT acitivy location:

`platformBuilds/<appConfig>_android/app/src/main/java/rnv/MainActivity.kt`

and your `MainActivity.kt` should have package:

```
package com.xxx.xxx

...
```

defined same as your app id id `platformBuilds/<appConfig>_android/app/build.gradle`

```
defaultConfig {
        applicationId "com.xxx.xxx"
```

normally this is autogenerated by rnv but I'll assume you're ejected so you need to pay attention to that

**Comment by pavjacko** [comment]
@Ivanov89 it's hard to debug ejected projects as it is not possible to for me to replicate your env and platformTemplates setup because it's only available in your project

but could you try following:

 navigate to `./platformBuilds/<appConfig>_android` and run `./gradlew assembleDebug --debug -x bundleReleaseJsAndAssets` manually

and see/share exact error do you get?

**Comment by Ivanov89** [comment]
@pavjacko , ok so after the above command that is the exact error: 

` vice] Worker lease root.1 completed (0 worker(s) in use)
2020-07-06T12:46:44.040+0300 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 6: released lock on root.1
2020-07-06T12:46:44.040+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring project ':app'.
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to notify project evaluation listener.
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > 'org.gradle.api.file.DirectoryProperty org.gradle.api.file.ProjectLayout.directoryProperty(org.gradle.api.provider.Provider)'
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2020-07-06T12:46:44.041+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
2020-07-06T12:46:44.042+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2020-07-06T12:46:44.042+0300 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
2020-07-06T12:46:44.042+0300 [WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
2020-07-06T12:46:44.042+0300 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
2020-07-06T12:46:44.042+0300 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1s
2020-07-06T12:46:44.042+0300 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
2020-07-06T12:46:44.042+0300 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
2020-07-06T12:46:44.054+0300 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
2020-07-06T12:46:44.062+0300 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
2020-07-06T12:46:44.063+0300 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.014 secs
2020-07-06T12:46:44.064+0300 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Build Output Cleanup Cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/buildOutputCleanup)
2020-07-06T12:46:44.064+0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Build Output Cleanup Cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/buildOutputCleanup).
2020-07-06T12:46:44.065+0300 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-rule (/Users/Ivanov/.gradle/caches/6.3/md-rule)
2020-07-06T12:46:44.066+0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-rule (/Users/Ivanov/.gradle/caches/6.3/md-rule).
2020-07-06T12:46:44.066+0300 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (/Users/Ivanov/.gradle/caches/6.3/md-supplier)
2020-07-06T12:46:44.066+0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (/Users/Ivanov/.gradle/caches/6.3/md-supplier).
2020-07-06T12:46:44.067+0300 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
2020-07-06T12:46:44.068+0300 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
2020-07-06T12:46:44.068+0300 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for checksums cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/checksums)
2020-07-06T12:46:44.068+0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on checksums cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/checksums).
2020-07-06T12:46:44.069+0300 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/6.3/fileHashes)
2020-07-06T12:46:44.069+0300 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/6.3/fileHashes).
2020-07-06T12:46:44.069+0300 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryStore] VCS Checkout Cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/vcs-1) has last been fully cleaned up 0 hours ago
2020-07-06T12:46:44.069+0300 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/vcs-1) was closed 0 times.
2020-07-06T12:46:44.069+0300 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS metadata (/Users/Ivanov/Desktop/Development.nosync/LobbyApp-RNV/cms-casino-app/platformBuilds/cmscasino-stage_android/.gradle/6.3/vcsMetadata-1) was closed 0 times.
2020-07-06T12:46:44.079+0300 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
2020-07-06T12:46:44.208+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@6b92fe48
2020-07-06T12:46:44.208+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 17: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
2020-07-06T12:46:44.209+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Success[value=org.gradle.launcher.exec.BuildActionResult@61eaec38] from daemon DaemonInfo{pid=28481, address=[b2e90d32-f9f6-4e79-a3d7-8a736f520d37 port:64862, addresses:[/127.0.0.1]], state=Idle, lastBusy=1594028768606, context=DefaultDaemonContext[uid=7ed82f8b-d85b-4a90-a32d-304a3583bdd1,javaHome=/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home,daemonRegistryDir=/Users/Ivanov/.gradle/daemon,pid=28481,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=BG,-Duser.language=en,-Duser.variant]} (build should be done).
2020-07-06T12:46:44.209+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
2020-07-06T12:46:44.209+0300 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop`

**Comment by pavjacko** [comment]
@Ivanov89 hmm seem very generic:

FAILURE: Build failed with an exception. 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
* What went wrong: 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring project ':app'. 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to notify project evaluation listener. 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > 'org.gradle.api.file.DirectoryProperty org.gradle.api.file.ProjectLayout.directoryProperty(org.gradle.api.provider.Provider)' 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try: 2020-07-06T12:46:44.041+0300 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. Run with --scan to get full insights. 2020-07-06T12:46:44.042+0300 
[ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1s 2020-07-06T12:46:44.042+0300 



but this is curious:
BUILD FAILED in 1s

indicates something fundamental is to right. maybe your SDK?
could you check
`platformBuilds/<appConfig>_android/local.properties` see if you have correct paths?

also you might open `platformBuilds/<appConfig>_android` directly in Android Studio and try to run it from there see if you won't get some immediate issues with your android setup?

**Comment by CiaranPearse** [comment]
@pavjacko Those are identical. Also I didn't eject. This is a fresh project pretty much put of the box.

The issue for me has popped up again. But only on AndroidTV. Android (phone) works fine as well as iOs & Web.

**Comment by pavjacko** [comment]
@CiaranPearse could you check following:

- what is your JDK version? mind you only 1.8.x is recommended as stable to use (tested with `1.8.0_131`)
- what is your gradle version? androidtv has been tested specifically with distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
- what is your buildToolsVersion in build.gradle? androidtv has been tested with `buildToolsVersion '28.0.0'`

**Comment by Ivanov89** [comment]
@pavjacko , I changed that line from `gradle-wrapper.properties`to : 

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip` , because it was 4.0.4 оr something like that and now it is working !  : )


Thanks for your help anyway!
Todor

**Comment by za-rakib** [comment]
any one solve this issue??
