### ISSUE TITLE
Tizen build release not working - Promise error

### ISSUE THREAD

**Issue by redgoalsuk** [pavjacko/renative#647]
**Describe the bug**
Error during compiling release for tizen

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command 'rnv build -p tizen -s release'
2. See error

**Expected behavior**
Tizen build

**Screenshots or copy&paste**
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ error ] [platform configure] Build scheme you picked does not exists.
[ task ] [platform configure] You need to specify scheme[1]
? Pick one of available buildSchemes (Use arrow keys)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/usr/local/lib/node_modules/rnv/node_modules/inquirer/lib/prompts/list.js:121:53)
    at MapSubscriber._next (/usr/local/lib/node_modules/rnv/node_modules/rxjs/src/internal/operators/map.ts:84:29)
    at MapSubscriber.Subscriber.next (/usr/local/lib/node_modules/rnv/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at TakeSubscriber._next (/usr/local/lib/node_modules/rnv/node_modules/rxjs/src/internal/operators/take.ts:92:24)
    at TakeSubscriber.Subscriber.next (/usr/local/lib/node_modules/rnv/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at Interface.handler (/usr/local/lib/node_modules/rnv/node_modules/rxjs/src/internal/observable/fromEvent.ts:201:20)
    at Interface.emit (events.js:203:15)
    at Interface.EventEmitter.emit (domain.js:448:20)
    at Interface._onLine (readline.js:308:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:937:14)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:203:15)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1073:36)
    at ReadStream.emit (events.js:198:13)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Node Version 10.19.0
-   RNV Version 0.31.3

**Additional context**
Been stuck on this for a couple of days, would appreciate some guidance.

**Comment by chmiiller** [comment]
Just to add more info here, I've just tested this command on macOS and it's worked just fine:
Desktop (please complete the following information):

OS: macOS Catalina 10.15.7
Node Version 10.20.1
RNV Version 0.31.3
