### ISSUE TITLE
Platform firetv not supported by any registered engine

### ISSUE THREAD

**Issue by yanv1991** [pavjacko/renative#655]
**Describe the bug**
Getting error after running a new project with the hello world template

**To Reproduce**
- generate a new brand project with hello world template
- add index.firetv.js file
- run `rnv run -p firetv`

1. Run command 'rnv run -p firetv'
2. See error

**Expected behavior**
The app should run correctly

**Screenshots or copy&paste**
```
[ warn ] Platform firetv not supported by any registered engine. SKIPPING...
│ [ warn ] Platform webtv not supported by any registered engine. SKIPPING...
│ [ error ] Cound not find suitable executor for task run
Error: Cound not find suitable executor for task run
    at getEngineRunner (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/src/core/engineManager/index.js:116:15)
    at getEngineRunner (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/src/core/engineManager/index.js:332:24)
    at tryCatch (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:118:21)
    at tryCatch (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:63:40)
    at invoke (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:154:20)
    at /Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:189:11
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:188:16)
    at AsyncIterator.enqueue (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:211:13)
    at AsyncIterator.next (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:118:21)
    at Object.exports.async (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:238:14)
    at findSuitableTask (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/src/core/engineManager/index.js:191:33)
    at run$ (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/src/cli/index.js:28:32)
    at tryCatch (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:118:21)
    at tryCatch (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:63:40)
    at invoke (/Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:154:20)
    at /Users/ynicaragua/.nvm/versions/node/v12.15.0/lib/node_modules/rnv/node_modules/regenerator-runtime/runtime.js:164:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Desktop (please complete the following information):**

-   OS: mac OS 10.15.17
-   Node Version 12.15.0
-   RNV Version [e.g. 0.31.3]

**Additional context**

**Comment by vvsamin** [comment]
FireTV platform support was added in rnv@0.32.0-alpha.25 https://github.com/pavjacko/renative/commit/2b4ac07e5ea1cbd4d3547d8a2c0f3c325dd6477e

**Comment by yanv1991** [comment]
@vvsamin I tried with that tag version but getting an error about missing engine

**Comment by yanv1991** [comment]
looks like the firetv runs as a normal androidtv app
