### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by caspervanpomeren** [pavjacko/renative#673]
**Describe the bug**
I am trying to just run rnv by following the quick start found here:
https://renative.org/docs/intro-quickstart

Unfortunately it throws an error that it cannot find specific modules.

**To Reproduce**

1. Run command rnv
2. Select new
3. Select all recommended / press enter
4. cd to app
5. Run command rnv run -p web
6. Try going to http://127.0.0.1:8080 (shows: "Problem loading page");
7. Git bash throws error

**Expected behavior**
I would expect it to run and host the hello world template on 127.0.0.1:8080.

**Screenshots or copy&paste**
Output of the command: rnv run -p web -i

```
Dev server running at: http://127.0.0.1:8080


_execute: npx cross-env PLATFORM=web  C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack-dev-server\bin\webpack-dev-server.js -d --devtool source-map --config D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\webpack.config.dev.js  --inline --hot --colors --content-base D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\server --history-api-fallback --port 8080 --mode=development
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'D:\Code'
Require stack:
- D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-cli\bin\convert-argv.js  
- D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-dev-server\bin\webpack-dev-server.js
- C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\import-local\index.js      
- C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at WEBPACK_OPTIONS (D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at Object.<anonymous> (D:\Code Journey\Projecten\ProjectFolder\myApp\node_modules\webpack-dev-server\bin\webpack-dev-server.js:87:55) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Code Journey\\Projecten\\ProjectFolder\\myApp\\node_modules\\webpack-cli\\bin\\convert-argv.js',
    'D:\\Code Journey\\Projecten\\ProjectFolder\\myApp\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\rnv\\node_modules\\import-local\\index.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\rnv\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
undefined
COMMAND: 

npx cross-env PLATFORM=web  C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack-dev-server\bin\webpack-dev-server.js -d --devtool source-map --config D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\webpack.config.dev.js  --inline --hot --colors --content-base D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\server --history-api-fallback --port 8080 --mode=development

FAILED with ERROR:

Command failed with exit code 1 (Unknown system error -1): npx cross-env PLATFORM=web C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack-dev-server\bin\webpack-dev-server.js -d --devtool source-map --config D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\webpack.config.dev.js --inline --hot --colors --content-base D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\server --history-api-fallback --port 8080 --mode=development

Error: Command failed with exit code 1 (Unknown system error -1): npx cross-env PLATFORM=web C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack-dev-server\bin\webpack-dev-server.js -d --devtool source-map --config D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\webpack.config.dev.js --inline --hot --colors --content-base D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\server --history-api-fallback --port 8080 --mode=development
    at makeError (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


[ hook ] [run] executePipe ('run:after')
buildHooks
[ task ] <= run

 $ rnv run -p web -i - Done! �
┌──────────────────────────────────────────────────────────────────────────────┐
│  �  SUMMARY | 4/26/2021, 20:01:20                                           │
│  $ rnv run -p web -i                                                         │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.3                                               │
│  Project Name ($package.name): myApp                                    │
│  Project Version ($package.version): 0.1.0                              │
│  Workspace ($.workspaceID): rnv                                         │
│  Platform (-p): web                                                     │
│  Engine ($.platforms.web.engine): engine-rn-web                         │
│  App Config (-c): helloworld                                            │
│  Build Scheme (-s): debug                                               │
│  Supported Platforms: web                                          │
│  Env Info: win32 | x64 | node v12.16.3                                  │
│  Executed Time: 0h:0m:4s:882ms                                          │
│                                                                              │
│ [ warn ] [project configure] Extra platform ios will be ignored because it's not configured 
in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform tvos will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform macos will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform windows will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform tizen will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform tizenmobile will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform tizenwatch will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform webos will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform chromecast will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform firefoxos will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform firefoxtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform kaios will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│                                                                              │
│  Project location:                                                           │
│  D:\Code Journey\Projecten\ProjectFolder\myApp\platformBuilds\helloworld_web\project        
                                                                                           │  
└──────────────────────────────────────────────────────────────────────────────┘
```

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro
-   Node Version: v12.16.3
-   RNV Version: 0.31.3

**Additional context**
I tried it with other platforms as well (so more than just the Web platform) and I got the same result.

What am I missing?

**Comment by caspervanpomeren** [comment]
Ok, so the problem is, it looks for: 
`
Error: Cannot find module 'D:\Code'`

But it should be:

`D:\Code Journey\etc..\etc..`

So somehow the spaces in the folder name causes this error, because when I remove all spaces in the folder names it suddenly works. This isn't ideal, but I have no alternative, so if anyone has, please let me know.
